name: Python CI

on:
  push:
    branches:
      - jeongtae  # jeongtae 브랜치에 푸시될 때 CI 실행
  pull_request:
    branches:
      - jeongtae  # jeongtae 브랜치로 PR을 보낼 때 CI 실행

jobs:
  test:
    runs-on: ubuntu-latest  # CI 작업은 최신 Ubuntu에서 실행
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 최신 버전의 checkout 액션 사용

      - name: Set up Python
        uses: actions/setup-python@v4  # 최신 버전의 setup-python 액션 사용
        with:
          python-version: '3.9'

      - name: Run Python script
        run: python main.py  # main.py 실행
